### ISSUE TITLE
ARE YOU LOST 

### ISSUE THREAD

**Issue by Lotusninja400** [Techno274721/WORK-TOGETHER#1]
Help me people

**Comment by Techno274721** [comment]
HOW?

**Comment by Techno274721** [comment]
Hello i see you where active Yesterday need help? we can zoom

**Comment by Lotusninja400** [comment]
Do something

**Comment by Lotusninja400** [comment]
plssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

**Comment by Lotusninja400** [comment]
¬_¬

**Comment by Techno274721** [comment]
now?

**Comment by Techno274721** [comment]
wait a momment

**Comment by Techno274721** [comment]
@Lotusninja400 @KINGPROTOG  we can zoom tommorow at any time except 2-5

**Comment by Techno274721** [comment]
Wasn't usefull
